
with stg_salesforce_user as (

    select * from {{ ref("stg_salesforce__user") }}

),

dim_user as (
    select
        user_id,
        username,
        firstname,
        lastname,
        companyname,
        division,
        department,
        title,
        street,
        city,
        state,
        postalcode,
        country,
        latitude,
        longitude,
        geocodeaccuracy,
        email,
        senderemail,
        sendername,
        signature,
        stayintouchsubject,
        stayintouchsignature,
        stayintouchnote,
        phone,
        fax,
        mobilephone,
        alias,
        communitynickname,
        isactive,
        issystemcontrolled,
        timezonesidkey,
        localesidkey,
        receivesinfoemails,
        receivesadmininfoemails,
        emailencodingkey,
        usertype,
        usersubtype,
        startday,
        endday,
        languagelocalekey,   
        createddate,
        createdbyid,
        lastmodifieddate,
        lastmodifiedbyid, 
        numberoffailedlogins,
        suaccessexpirationdate,
        suorgadminexpirationdate,
        offlinetrialexpirationdate,
        wirelesstrialexpirationdate,
        offlinepdatrialexpirationdate,
        forecastenabled,
        extension,
        federationidentifier,
        aboutme,
        loginlimit,
        profilephotoid,
        digestfrequency,
        defaultgroupnotificationfrequency,
        jigsawimportlimitoverride,
        sharingtype,
        chatteradoptionstage,
        chatteradoptionstagemodifieddate,
        isprofilephotoactive,
        individualid,
        globalidentity
    from stg_salesforce_user
)
select * from dim_user 